config/routes.rb
Rails.application.routes.draw do
  root 'mop_info_pages#mission'

  get 'mission', to: 'mop_info_pages#mission'
  get 'volunteer', to: 'mop_info_pages#volunteer'
  get 'hours', to: 'mop_info_pages#hours'

  resources :inventories
    get 'inventories/filter/:filter' => 'inventories#index', as: :filtered_inventories

  resources :categories

  resources :donators
    get 'donators/filter/:filter' => 'donators#index', as: :filtered_donators

  resources :links

  resources :events
    get 'events/filter/:filter' => 'events#index', as: :filtered_events

  resources :users
    get 'signup' => 'users#new'
    get 'users/filter/:filter' => 'users#index', as: :filtered_users

  resource :session
    get 'signin' => 'sessions#new'
    post 'signin' => 'sessions#create'
end

app/models/donator.rb
class Donator < ActiveRecord::Base
  before_validation :generate_slug
  
  validates :name, presence: true, uniqueness: true
  validates :slug, uniqueness: true

  scope :current_donator, -> { where(:current => true) }
  scope :former_donator, -> { where(:current => false) }

  def to_param
    slug
  end

  def generate_slug
    self.slug ||= name.parameterize if name
  end
end

app/controllers/donators_controller.rb
class DonatorsController < ApplicationController
  before_action :set_donator, only: [:show, :edit, :update, :destroy]
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    case params[:filter]
    when 'former'
      @donators = Donator.former_donator
    when 'all'
      @donators = Donator.all
    else
      @donators = Donator.current_donator
    end
  end

  def show; end

  def new
    @donator = Donator.new
  end

  def create
    @donator = Donator.new(donator_params)
    if @donator.save
      flash[:notice] = "Donator successfully created!"
      redirect_to @donator
    else
      render :new
    end
  end

  def edit; end

  def update
    if @donator.update(donator_params)
      flash[:notice] = "Donator successfully updated!"
      redirect_to @donator
    else
      render :edit
    end
  end

  def destroy
    @donator.destroy
    flash[:notice] = "Donator successfully deleted!"
    redirect_to donators_url
  end

  private
    def donator_params
      params.require(:donator).permit!
    end

    def set_donator
      @donator = Donator.find_by!(slug: params[:id])
    end
  #private end
end

app/helpers/donators_helper.rb
module DonatorsHelper
  def image_for(donator)
    if donator.logo_link.blank?
      image_tag('placeholder.png')
    else
      image_tag(donator.logo_link)
    end
  end
end

app/views/donators/_form.html.erb
<%= bootstrap_form_for(@donator) do |f| %>
  <%= render "shared/errors", object: @donator %>
  <fieldset>
    <%= f.text_field :name, autofocus: true %>
    <%= f.text_field :website %>
    <%= f.email_field :email %>
    <%= f.text_field :donation %>
    <%= f.text_area :description, rows: 3 %>
    <%= f.text_field :address %>
    <%= f.text_field :phone %>
    <%= f.text_field :logo_link, placeholder: "GIF, JPG, or PNG file name" %>
    <% if current_user_admin? %>
      <%= f.check_box :current, label: 'Current Donator?' %>
    <% end %>
    <%= f.submit(class: 'btn btn-success') %>
    <%= link_to "Cancel", donators_path, class: 'btn btn-warning' %>
  </fieldset>
<% end %>

app/views/donators/edit.html.erb
<% content_for(:title, "edititing #{@donator.name}") %>

<h1>Edit Donator</h1>

<%= render 'form' %>

app/views/donators/index.html.erb
<h1>Our wonderfully generous donators...</h1>

<% @donators.each do |donator| %>
  <article>
    <header>
      <%= image_for(donator) %>
      <h2><%= link_to donator.name, donator %></h2>
    </header>
    <p>
      <a href="<%= donator.website %>" target="_blank"><%= donator.website%></a>
    </p>
    <h4>What they have given to us to share...</h4>
    <p class="indent">
      ~ <%= donator.donation %>
    </p>
    <br><br>
  </article>
<% end %>

app/views/donators/new.html.erb
<% content_for(:title, "new donator") %>

<h1>Create Donator</h1>

<%= render 'form' %>

app/views/donators/show.html.erb
<% content_for(:title, @donator.name) %>

<article>
  <header align="center">
    <%= image_for(@donator) %>
    <h1><%= @donator.name %></h1>
    <p>
      <a href="<%= @donator.website %>" target="_blank"><%= @donator.website %></a>
    </p>
    <p>
      <%= @donator.address %>
    </p>
    <p>
      <%= @donator.phone %>
    </p>
    <p>
      <%= mail_to(@donator.email) %>
    </p>
  </header>
  <br>
  <p>
    <%= @donator.description %>
  </p>
  <br>
  <h4>What they have given to us to share...</h4>
  <p class="indent">
    ~ <%= @donator.donation %>
  </p>
  <nav>
    <% if current_user_admin? %>
      <%= link_to "Edit Donator", edit_donator_path(@donator), class: 'btn btn-warning' %>
      <%= link_to "Delete Donator", donator_path(@donator), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure you want to permanently delete your account?' } %>
    <% end %>
  </nav>
</article>