config/routes.rb
Rails.application.routes.draw do
  root 'mop_info_pages#mission'

  get 'mission', to: 'mop_info_pages#mission'
  get 'volunteer', to: 'mop_info_pages#volunteer'
  get 'hours', to: 'mop_info_pages#hours'

  resources :inventories
    get 'inventories/filter/:filter' => 'inventories#index', as: :filtered_inventories

  resources :categories

  resources :donators
    get 'donators/filter/:filter' => 'donators#index', as: :filtered_donators

  resources :links

  resources :events
    get 'events/filter/:filter' => 'events#index', as: :filtered_events

  resources :users
    get 'signup' => 'users#new'
    get 'users/filter/:filter' => 'users#index', as: :filtered_users

  resource :session
    get 'signin' => 'sessions#new'
    post 'signin' => 'sessions#create'
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  before_validation :generate_slug

  validates :name, presence: true

  validates :name, uniqueness: true
  validates :slug, uniqueness: true

  scope :low, -> { where(:running_low => true).order(name: :asc) }

  def to_param
    slug
  end

  def generate_slug
    self.slug ||= name.parameterize if name
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]
  
  def index
    case params[:filter]
    when 'all'
      @inventories = Inventory.all
    else
      @inventories = Inventory.low
    end
    
  end

  def show; end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.name = params[:inventory][:name].titleize
    if @inventory.save
      flash[:notice] = "Yay for more in the pantry!"
      redirect_to @inventory
    else
      render :new
    end
  end

  def edit; end

  def update
    @inventory.name = params[:inventory][:name].titleize
    if @inventory.update(inventory_params)
      flash[:notice] = "Inventory successfully updated!"
      redirect_to @inventory
    else
      render :edit
    end
  end

  def destroy
    @inventory.destroy
    flash[:notice] = "Inventory successfully deleted!"
    redirect_to inventories_url
  end

  private
    def inventory_params
      params.require(:inventory).permit!
    end

    def set_inventory
      @inventory = Inventory.find_by!(slug: params[:id])
    end
  # private end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= bootstrap_form_for(@inventory) do |f| %>
  <%= render "shared/errors", object: @inventory %>
  <fieldset>
    <%= f.text_field :name, autofocus: true %>
    <%= f.text_field :pref_size, label: "Prefered Size" %>
    <h5>Running low?</h5>
    <%= f.form_group :running_low do %>
      <%= f.radio_button :running_low, true, label: "Yes", inline: true %>
      <%= f.radio_button :running_low, false, label: "No", inline: true %>
    <% end %>
    <% if @inventory.new_record? %>
      <%= f.submit "Create", class: 'btn btn-success' %>
    <% else %>
      <%= f.submit "Update", class: 'btn btn-success' %>
    <% end %>
    <%= link_to "Cancel", inventories_path, class: 'btn btn-warning' %>
  </fieldset>
<% end %>

app/views/inventories/edit.html.erb
<% content_for(:title, "edititing #{@inventory.name}") %>

<h1>Edit this inventory item</h1>

<%= render 'form' %>

app/views/inventories/index.html.erb
<h1>Our current inventory needs...</h1>
<h2>These are all the items we have on our shelves.  If you are thinking of making a non-monetary donation, please consider picking up these items first.  Thank you.</h2>

<% @inventories.each do |inventory| %>
  <article>
    <header>
      <h3><%= link_to inventory.name, inventory %></h3>
      <%= link_to '' %>
    </header>
  </article>
<% end %>

app/views/inventories/new.html.erb
<% content_for(:title, "new inventory") %>

<h1>Add in the new inventory item</h1>

<%= render 'form' %>

app/views/inventories/show.html.erb
<% content_for(:title, @inventory.name) %>

<article>
  <header>
    <h1><%= @inventory.name %></h1>
    <p>
      Prefered Size: <%= @inventory.pref_size %>
    </p>
    <p>
      Running Low?: <%= @inventory.running_low %>
    </p>  
  </header>
  <br>
  <nav>
    <% if current_user_admin? %>
      <%= link_to "Edit Inventory", edit_inventory_path(@inventory), class: 'btn btn-warning' %>
      <%= link_to "Delete Inventory", inventory_path(@inventory), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure you want to permanently delete your account?' } %>
      <%= link_to "Add Another", new_inventory_path, class: 'btn btn-success' %>
    <% end %>
  </nav>
</article>