config/routes.rb
Rails.application.routes.draw do
  root 'mop_info_pages#mission'

  get 'mission', to: 'mop_info_pages#mission'
  get 'volunteer', to: 'mop_info_pages#volunteer'
  get 'hours', to: 'mop_info_pages#hours'

  resources :inventories
    get 'inventories/filter/:filter' => 'inventories#index', as: :filtered_inventories

  resources :categories

  resources :donators
    get 'donators/filter/:filter' => 'donators#index', as: :filtered_donators

  resources :links

  resources :events
    get 'events/filter/:filter' => 'events#index', as: :filtered_events

  resources :users
    get 'signup' => 'users#new'
    get 'users/filter/:filter' => 'users#index', as: :filtered_users

  resource :session
    get 'signin' => 'sessions#new'
    post 'signin' => 'sessions#create'
end

app/models/event.rb
class Event < ActiveRecord::Base
  before_validation :generate_slug
  
  validates :title, :date_start, :date_end, :details, presence: true
  validates :details, length: { minimum: 25 }
  validates :title, presence: true, uniqueness: true
  validates :slug, uniqueness: true

  scope :happening_now, -> { where("? BETWEEN date_start AND date_end", Time.now).order(date_start: :asc) }
  scope :ended, -> {  where("date_end < ?", Time.now).order(date_end: :asc) }
  scope :upcoming, -> {  where("date_start > ?", Time.now).order(date_start: :asc) }

  def to_param
    slug
  end

  def generate_slug
    self.slug ||= title.parameterize if title
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :require_signin, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    case params[:filter]
    when 'ended'
      @events = Event.ended
    when 'upcoming'
      @events = Event.upcoming
    when 'all'
      @events = Event.all
    else
      @events = Event.happening_now
    end
  end

  def show; end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "Event successfully created!"
      redirect_to @event
    else
      render :new
    end
  end

  def edit; end

  def update
    if @event.update(event_params)
      flash[:notice] = "Event successfully updated!"
      redirect_to @event
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    flash[:notice] = "Event successfully deleted!"
    redirect_to events_url
  end

  private
    def event_params
      params.require(:event).permit!
    end

    def set_event
      @event = Event.find_by!(slug: params[:id])
    end
  # private end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= bootstrap_form_for(@event) do |f| %>
  <%= render "shared/errors", object: @event %>
  <fieldset>
    <%= f.text_field :title, autofocus: true %>
    <%= f.date_field :date_start %>
    <%= f.date_field :date_end %>
    <%= f.text_area :details, rows: 2 %>
    <%= f.submit(class: 'btn btn-success') %>
    <%= link_to "Cancel", events_path, class: 'btn btn-warning' %>
  </fieldset>
<% end %>

app/views/events/edit.html.erb
<% content_for(:title, "edititing #{@event.title}") %>

<h1>Editing Event: <%= @event.title %></h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1>Mount Olive Pantry is glad to be a part of the following events:</h1>

<% @events.each do |event| %>
  <article>
    <header>
      <h2><%= link_to event.title, event %></h2>
    </header>
    <p>
      <%= truncate(event.details, length: 40, separator: ' ') %>
    </p>
    <h4>Happening:</h4>
    <p>
       <%= event.date_start %> through <%= event.date_end %>
    </p>
  </article>
<% end %>

app/views/events/new.html.erb
<% content_for(:title, "new event") %>

<h1>Create Event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<% content_for(:title, @event.title) %>

<article>
  <header>
    <h1><%= @event.title %></h1>
  </header>
  <p>
    <%= @event.details %>
  </p>
  <h3>Dates</h3>
  <p>
    <%= @event.date_start %> through <%= @event.date_end %>
  </p>
  <nav>
    <% if current_user_admin? %>
      <%= link_to "Edit Event", edit_event_path(@event), class: 'btn btn-warning' %>
      <%= link_to "Delete Event", event_path(@event), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure you want to permanently delete your account?' } %>
    <% end %>
  </nav>
</article>