config/routes.rb
Rails.application.routes.draw do
  root 'mop_info_pages#mission'

  get 'mission', to: 'mop_info_pages#mission'
  get 'volunteer', to: 'mop_info_pages#volunteer'
  get 'hours', to: 'mop_info_pages#hours'

  resources :inventories
    get 'inventories/filter/:filter' => 'inventories#index', as: :filtered_inventories

  resources :categories

  resources :donators
    get 'donators/filter/:filter' => 'donators#index', as: :filtered_donators

  resources :links

  resources :events
    get 'events/filter/:filter' => 'events#index', as: :filtered_events

  resources :users
    get 'signup' => 'users#new'
    get 'users/filter/:filter' => 'users#index', as: :filtered_users

  resource :session
    get 'signin' => 'sessions#new'
    post 'signin' => 'sessions#create'
end

app/views/layouts/_header.html.erb
<div class="col-md-2"></div>

<div class="col-md-8" align='center'>
  <%= link_to "Mount Olive Pantry", root_path, {:style=>'color:#FFFFFF'} %>
  <h5>
    Partners in Compassion, Inc.</br>
    Located in the lower level of Christ Church ~ 369 Sandshore Road, Budd Lake ~ 862-251-3938</br>
  </h5>
</div>

<div class="col-md-2" align='center'>
    <% if current_user %>
      <div class="btn-group">
        <button type="button" class="btn btn-info">
          <%= current_user.name %>
        </button>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu dropdown-menu-right" role="menu">
          <li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
          <li><%= link_to "Delete Account", user_path(current_user), method: :delete, data: { confirm: 'Are you sure?' } %></li>
          <li class="divider"></li>
          <li><%= link_to 'Sign Out', session_path, method: :delete %></li>
        </ul>
      </div>
    <% else %>
      <%= link_to 'Become a Volunteer', signup_path, class: 'btn btn-primary' %>
      <%= link_to 'Volunteer Sign In', signin_path, class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="panel-group" id="accordian">

  <div class="panel panel-danger" id="panel1">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-target="#collapseOne" href="#collapseOne">
          learn more about</br>Mount Olive Pantry
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        <p><%= link_to 'Our Mission', mission_url %></p>
        <p><%= link_to "How Volunteers Help", volunteer_url %></p>
        <p><%= link_to "This Month's Hours", hours_url %></p>
      </div>
    </div>
  </div>

  <div class="panel panel-success" id="panel2">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-target="#collapseTwo" href="#collapseTwo" class="collapsed">
          Inventory
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        <p><%= link_to 'What We Need Most', inventories_path %></p>
        <p><%= link_to "Our Entire Inventory", filtered_inventories_path(:all) %></p>
        <% if current_user_admin? %>
          <p><%= link_to "Add New Inventory", new_inventory_path %></p>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="panel panel-warning" id="panel3">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-target="#collapseThree" href="#collapseThree" class="collapsed">
          Donators
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
        <p><%= link_to 'Our Donators', donators_path %></p>
        <% if current_user_admin? %>
          <p><%= link_to "All Recorded Donators", filtered_donators_path(:all) %></p>
          <p><%= link_to "Former Donators", filtered_donators_path(:former) %></p>
          <p><%= link_to "Add New Donator", new_donator_path %></p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="panel panel-warning" id="panel4">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-target="#collapseFour" href="#collapseFour" class="collapsed">
          Events
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse">
      <div class="panel-body">
        <p><%= link_to "Happening Now", events_path %></p>
        <p><%= link_to "Upcoming", filtered_events_path(:upcoming) %></p>
        <p><%= link_to "All Events", filtered_events_path(:all) %></p>
        <p><%= link_to "Ended", filtered_events_path(:ended) %></p>
        <% if current_user_admin? %>
          <p><%= link_to "Add New Event", new_event_path %></p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="panel panel-info" id="panel5">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-target="#collapseFive" href="#collapseFive" class="collapsed">
          Links
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse">
      <div class="panel-body">
        <p><%= link_to "Useful Links", links_path %></p>
        <% if current_user_admin? %>
          <p><%= link_to "Add New Link", new_link_path %></p>
        <% end %>
      </div>
    </div>
  </div>

  <% if current_user_admin? || current_user_approved? %>
    <div class="panel panel-danger" id="panel6">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-target="#collapseSix" href="#collapseSix" class="collapsed">
            Volunteers
          </a>
        </h4>
      </div>
      <div id="collapseSix" class="panel-collapse collapse">
        <div class="panel-body">
          <p><%= link_to "Our Volunteers", users_path %></p>
          <p><%= link_to "Site Admins", filtered_users_path(:site_admin) %></p>
          <p><%= link_to "Regulars", filtered_users_path(:regular) %></p>
          <% if current_user_admin? %>
            <p><%= link_to "Add New Volunteer", new_user_path %></p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrapper">
      <div id="header" class='navbar-fixed-top'>
        <%= render 'layouts/header' %>
      </div>
      <div id="content">
        <div id="main" role="main">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <div id="aside">
                <%= render 'layouts/sidebar' %>
              </div>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>